### ISSUE TITLE
[RENDERER] - Issue Colection

### ISSUE THREAD

**Issue by quarkus** [webtides/element-js#123]
Problems

- [x]  early return in template when "null" is returned 

- [x] ```<textarea>${this.value}</textarea>``` (this.value was an empty string) -> shall nbe tracked in: https://github.com/webtides/element-js/issues/133

**Comment by eddyloewen** [comment]
Problems:
* "=" sign in attribute will cause generating parts errors. E.g. link="/api/${resource}?id=${item.id}"

**Comment by quarkus** [comment]
probably related:
https://github.com/webtides/element-js/issues/122

**Comment by KinG-DE** [comment]
- no template update, if an HTML string is returned instead of just a plain string (or literal)

https://codepen.io/KingDE/pen/YzmabbL?editors=1010

**Comment by quarkus** [comment]
Moved findings to dedicated tickets as this gets to messy.
