### ISSUE TITLE
i18n fallback does not work as expected

### ISSUE THREAD

**Issue by MagnusPanter** [webtides/element-js#21]
The i18n method from the element-js package is not working as expected. 
The **fallback** you can define when calling the method is only used when you have a connection-error.

e.g.: `i18n('someForm.headline', 'Now or never')`

I was expecting that it uses the fallback string when the key or no translation for the key is available.
Right now it gives back the key 'someForm.headline' as the translation when I haven't got the key in my translationfiles.

**Comment by quarkus** [comment]
Totally true! Just came across this and wanted to raise the exact same issue!
