### ISSUE TITLE
pre v1.0.0 - housekeeping

### ISSUE THREAD

**Issue by quarkus** [webtides/element-js#46]
Find potential quirks and bloat to get rid of before 1.0 release.

- ~~globalStyles adoption naming (#globalStyles -> param)~~ #105
- ~~globalStyles adoption non inline styles~~ #105 
- ~~remove ShadyCSS~~ #99 
- remove custom logic for styles since constructable stylesheets are supported in all browsers now
- ~~remove i18n functionallity -> docs~~
- ~~remove LIT~~ #67 
- ~~document Migration Path from Lit to Vanilla~~
- ~~remove shadyRender~~ #67  
- ~~remove computed() map~~ #99 
- move define Methods (Injection, Properties etc. ) out of the instance  -> utility fns
- think about including property changes from within watchers to be processed in the same update cycle to avoid rendering multiple times

**Comment by eddyloewen** [comment]
Is this helpfull for a possible API in terms of globalStyles naming and adoption?!
https://lit.dev/playground/#gist=a2647fa2d6497596de238d0802f4f6e1

**Comment by eddyloewen** [comment]
@quarkus I think you already mentioned it somewhere else, but I would like to change the behaviour and especially the method parameters (default values) for the `dispatch` helper function. I think this would be the biggest breaking change of all

**Comment by quarkus** [comment]
Absolutely ...

I am not sure if we want to have the dependency but we can absolutely get inspired by the implement ;) .
