### ISSUE TITLE
Storeception: Stores as properties in Stores

### ISSUE THREAD

**Issue by quarkus** [webtides/element-js#90]
It might be usefull to have Store instances within Stores.

Wrapping Stores should probably become observer of the nested Store ..

**Comment by eddyloewen** [comment]
I actually thought that this is already be possible 🤷‍♂️ . I must really start looking more carefully through the PRs 😆 
But yeah! This can be a really nice thing as this will allow us to build truly reactive nested "objects"

**Comment by quarkus** [comment]
Haha .. @eddyloewen take a look the Draft MR i opened . It's not really complicated but we have to aggree on what a nested update should actually do.

requestUpdate (-> notify all observer by default ) && call watchers or simply call the watchers and leave the update decision to the observer.

**Comment by quarkus** [comment]
@eddyloewen i think the feature works and tests are happy. would be great if you could take a look at it again.
